import 'dart:io';

import 'package:excel/excel.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:material_lab/core/constants/app_strings.dart';
import 'package:material_lab/features/qc_manager/data/ncr_export_service.dart';
import 'package:material_lab/features/qc_manager/domain/ncr_filters.dart';
import 'package:material_lab/features/qc_manager/domain/ncr_kpis.dart';
import 'package:material_lab/features/qc_manager/domain/ncr_report_row.dart';

NcrReportRow _row(
  int id, {
  String status = 'Open',
  String severity = 'Major',
  String dueDate = '',
  String closedAt = '',
}) => NcrReportRow(
  findingId: id,
  inspectionId: 1,
  inspectionRefId: 'INS-1',
  code: 'NC-$id',
  severity: severity,
  description: 'defect $id',
  status: status,
  lotNo: 'LOT-$id',
  assignedToName: 'Ali',
  createdAt: '2026-01-0$id 09:00:00',
  dueDate: dueDate,
  closedAt: closedAt,
);

void main() {
  late Directory tmp;

  setUp(() async {
    AppText.arabic = false;
    tmp = await Directory.systemTemp.createTemp('ncr_export');
  });
  tearDown(() async {
    if (tmp.existsSync()) await tmp.delete(recursive: true);
  });

  NcrExportBundle bundle({
    List<NcrReportRow>? rows,
    NcrFilters? filters,
    NcrKpis? kpis,
    bool withPanels = true,
    DateTime? generatedAt,
  }) => NcrExportBundle(
    filters: filters ?? const NcrFilters(statuses: {'Open'}),
    kpis: kpis ?? const NcrKpis(total: 3, open: 2, overdue: 1, critical: 1),
    rows: rows ?? [_row(1), _row(2, severity: 'Critical')],
    aging: withPanels
        ? const [NcrAgingBucket.d0to7(2), NcrAgingBucket.d8to14(1)]
        : const [],
    topDefects: withPanels
        ? const [NcrTopDefect(code: 'D-CRACK', category: 'Surface', count: 4)]
        : const [],
    generatedBy: 'Hassan',
    generatedAt: generatedAt ?? DateTime(2026, 3, 4, 5, 6),
  );

  group('Excel export', () {
    test('writes the four sheets the plan names', () async {
      final result = await NcrExportService().exportExcel(
        bundle(),
        directory: tmp,
      );

      expect(File(result.path).existsSync(), isTrue);
      final book = Excel.decodeBytes(File(result.path).readAsBytesSync());

      expect(
        book.sheets.keys.toSet(),
        containsAll(['NCR_List', 'KPIs', 'Top_Defects', 'Aging']),
      );
    });

    test(
      'every filtered row lands in NCR_List, not just the visible page',
      () async {
        final rows = List.generate(57, (i) => _row(i + 1));
        final result = await NcrExportService().exportExcel(
          bundle(rows: rows),
          directory: tmp,
        );

        final sheet = Excel.decodeBytes(
          File(result.path).readAsBytesSync(),
        )['NCR_List'];

        // 57 data rows plus the header.
        expect(sheet.maxRows, rows.length + 1);
        expect(result.rowCount, 57);
      },
    );

    test('codes and statuses are stored verbatim, untranslated', () async {
      final result = await NcrExportService().exportExcel(
        bundle(
          rows: [_row(1, status: 'InProgress', severity: 'Critical')],
        ),
        directory: tmp,
      );
      final sheet = Excel.decodeBytes(
        File(result.path).readAsBytesSync(),
      )['NCR_List'];

      final headers = sheet.rows.first
          .map((c) => c?.value.toString() ?? '')
          .toList();
      final data = sheet.rows[1].map((c) => c?.value.toString() ?? '').toList();

      final severityCol = headers.indexOf('Severity');
      final statusCol = headers.indexOf('Status');

      expect(severityCol, isNonNegative, reason: 'headers were: $headers');
      expect(statusCol, isNonNegative, reason: 'headers were: $headers');
      expect(data[severityCol], 'Critical');
      expect(data[statusCol], 'InProgress');
    });

    test('the KPI sheet records the scope and provenance of the file', () async {
      final result = await NcrExportService().exportExcel(
        bundle(),
        directory: tmp,
      );
      final kpis = Excel.decodeBytes(
        File(result.path).readAsBytesSync(),
      )['KPIs'];

      String valueFor(String label) {
        for (final row in kpis.rows.skip(1)) {
          if (row.length < 2) continue;
          if (row[0]?.value.toString() == label) {
            return row[1]?.value.toString() ?? '';
          }
        }
        fail('no KPI row labelled "$label"');
      }

      expect(valueFor('Total'), '3');
      expect(valueFor('Generated by'), 'Hassan');
      expect(valueFor('Generated at'), contains('2026-03-04'));
      // The scope must name the filter, so a file found later says what it is a
      // report of rather than silently claiming to cover everything.
      expect(valueFor('Scope'), contains('Open'));
    });

    test('an empty report still produces a readable workbook', () async {
      final result = await NcrExportService().exportExcel(
        bundle(rows: const [], withPanels: false),
        directory: tmp,
      );
      final sheet = Excel.decodeBytes(
        File(result.path).readAsBytesSync(),
      )['NCR_List'];

      expect(sheet.maxRows, 1);
      expect(result.rowCount, 0);
    });
  });

  group('PDF export', () {
    test('writes a non-trivial file', () async {
      final result = await NcrExportService().exportPdf(
        bundle(),
        directory: tmp,
      );
      final bytes = File(result.path).readAsBytesSync();

      expect(result.path, endsWith('.pdf'));
      expect(bytes.length, greaterThan(800));
      expect(String.fromCharCodes(bytes.take(5)), '%PDF-');
    });

    test(
      'scales with the row count instead of always printing one page of data',
      () async {
        final small = await NcrExportService().exportPdf(
          bundle(rows: [_row(1)]),
          directory: tmp,
        );
        final large = await NcrExportService().exportPdf(
          bundle(rows: List.generate(80, (i) => _row(i + 1))),
          directory: tmp,
        );

        expect(
          File(large.path).lengthSync(),
          greaterThan(File(small.path).lengthSync()),
        );
        expect(large.rowCount, 80);
      },
    );

    test('an empty report does not throw', () async {
      final result = await NcrExportService().exportPdf(
        bundle(rows: const [], withPanels: false),
        directory: tmp,
      );
      expect(File(result.path).existsSync(), isTrue);
    });

    test('the result names the scope it was built from', () async {
      final result = await NcrExportService().exportPdf(
        bundle(
          filters: const NcrFilters(statuses: {'Open'}, lotNo: 'LOT-9'),
        ),
        directory: tmp,
      );
      expect(result.scope, contains('LOT-9'));
    });
  });

  test(
    'the filename is timestamped so exports do not overwrite each other',
    () async {
      final service = NcrExportService();
      final a = await service.exportPdf(bundle(), directory: tmp);
      final b = await service.exportPdf(
        bundle(generatedAt: DateTime(2026, 3, 4, 5, 7)),
        directory: tmp,
      );

      expect(a.path, isNot(b.path));
      expect(a.path, contains('20260304_0506'));
      expect(b.path, contains('20260304_0507'));
    },
  );
}
